"""Export utilities for transcription results.

Supports SRT (subtitles), plain text, and HTML export formats.
"""

import json
from datetime import timedelta


def export_srt(text: str, duration_sec: float = 0, words_per_segment: int = 8) -> str:
    """Export transcription as SRT subtitle file content.

    Splits text into segments of words_per_segment words with timestamps.
    If duration_sec is provided, timestamps are calculated from actual audio duration.
    Otherwise, estimates ~4 words per second.
    """
    words = text.split()
    if not words:
        return ""

    segments = []
    for i in range(0, len(words), words_per_segment):
        chunk = words[i:i + words_per_segment]
        segments.append(" ".join(chunk))

    total_segments = len(segments)
    if duration_sec > 0:
        sec_per_segment = duration_sec / total_segments
    else:
        sec_per_segment = len(segments[0].split()) / 4.0  # ~4 words/sec

    lines = []
    for idx, segment in enumerate(segments):
        start = idx * sec_per_segment
        end = (idx + 1) * sec_per_segment
        start_str = _format_srt_time(start)
        end_str = _format_srt_time(end)
        lines.append(f"{idx + 1}")
        lines.append(f"{start_str} --> {end_str}")
        lines.append(segment)
        lines.append("")

    return "\n".join(lines)


def _format_srt_time(seconds: float) -> str:
    """Format seconds to SRT timestamp (HH:MM:SS,mmm)."""
    td = timedelta(seconds=seconds)
    hours = int(td.total_seconds() // 3600)
    minutes = int((td.total_seconds() % 3600) // 60)
    secs = int(td.total_seconds() % 60)
    millis = int((td.total_seconds() % 1) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def export_text(text: str, filename: str = "transcription.txt") -> dict:
    """Export as plain text. Returns {content, filename, mime}."""
    return {
        "content": text,
        "filename": filename,
        "mime": "text/plain",
    }


def export_html(text: str, title: str = "Transcription") -> str:
    """Export as formatted HTML."""
    paragraphs = text.split("\n")
    p_html = "\n".join(f"  <p>{p.strip()}</p>" for p in paragraphs if p.strip())

    return f"""<!DOCTYPE html>
<html lang="yo">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body {{ font-family: 'Inter', system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.7; color: #1a1a2e; }}
    h1 {{ font-size: 1.5rem; margin-bottom: 1rem; }}
    p {{ margin: 0.5rem 0; font-size: 1rem; }}
    .meta {{ color: #666; font-size: 0.875rem; margin-bottom: 2rem; }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  <div class="meta">Generated by Bámi-Sọ̀rọ̀ Yoruba STT</div>
  {p_html}
</body>
</html>"""


def export_json(text: str, metadata: dict = None) -> str:
    """Export as JSON with metadata."""
    data = {
        "text": text,
        "source": "bami-soro",
        "metadata": metadata or {},
    }
    return json.dumps(data, ensure_ascii=False, indent=2)
